//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bridge
    {
        public int id { get; set; }
        public Nullable<int> jni { get; set; }
        public Nullable<int> city { get; set; }
        public Nullable<double> length { get; set; }
    
        public virtual city city1 { get; set; }
    }
}
